spring:
  datasource:
    url: jdbc:postgresql://localhost:5700/dbsocial
    username: usersocial
    password: dbsocial
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update